name: Deploy site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout 
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
    
    - name: Build
      env:
        TZ: 'Europe/Berlin'
      run: hugo --minify

    - name: "Deploy to GitHub Pages"
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

    - name: Install SSH Client and SSHPass
      run: sudo apt-get update && sudo apt-get install -y openssh-client sshpass

    - name: Upload files via SFTP
      env:
        SFTP_HOST:  "s145.goserver.host"
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      run: |
        sshpass -p "$SFTP_PASSWORD" sftp -o StrictHostKeyChecking=no $SFTP_USERNAME@$SFTP_HOST <<EOF
          mkdir -p $SFTP_TARGET_DIR
          put -r public/* /home/www/michaeldorner.de/
          bye
