name: Deploy site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout 
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
    
    - name: Build
      env:
        TZ: 'Europe/Berlin'
      run: hugo --minify

    - name: "Deploy to GitHub Pages"
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public



    - name: "Deploy to Webgo"
      uses: milanmk/actions-file-deployer@master
      with:
        remote-protocol: sftp

        # Credentials for SFTP access to server using GitHub secrets
        remote-host: s145.goserver.host
        remote-user: ${{ secrets.SFTP_USER }}
        remote-password: ${{ secrets.SFTP_PASSWORD }}

        local-path: ./public/
        remote-path: /home/www/michaeldorner.de/

        # Port for SFTP access to server
        remote-port: 22
        sync: full
        debug: true